apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: authorization-db
  name: authorization-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authorization-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: authorization-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: store-authorization
            - name: POSTGRES_PASSWORD
              value: wtf123
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: authorization-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: authorization-db-data
      restartPolicy: Always
      volumes:
        - name: authorization-db-data
          persistentVolumeClaim:
            claimName: authorization-db-data
