version: "3.9"
services:
  eureka-server:
    build:
      context: ./eureka_server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - EUREKA_INSTANSE_PREFERIPADDRESS=true

  store-authorization:
    build:
      context: ./store_authorization
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - authorization_db
      - token-storage
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://authorization_db:5432/store_authorization
      - SPRING_DATA_REDIS_HOST=token-storage
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - EUREKA_INSTANSE_PREFERIPADDRESS=true

  optical-shop:
    build:
      context: ./optical_shop
    ports:
      - "8888:8888"
    depends_on:
      - optical_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://optical_db:5432/OpticalShop
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - EUREKA_INSTANSE_PREFERIPADDRESS=true

  authorization_db:
    image: postgres
    restart: always
    volumes:
      - ./sql/schema-postgresql.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wtf2281337
      - POSTGRES_DB=store_authorization
    ports:
      - "5432:5432"

  optical_db:
    image: postgres
    restart: always
    volumes:
      - ./sql/schema-postgresql.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wtf2281337
      - POSTGRES_DB=OpticalShop
    ports:
      - "5433:5432"

  token-storage:
    image: redis
    restart: always
    ports:
      - "6379:6379"