version: "3.9"
services:
  eureka-server:
    build:
      context: eureka_server
      dockerfile: eureka_server/Dockerfile
    networks:
      - my-network
    ports:
      - "8761:8761"

  config-server:
    build:
      context: config_server
      dockerfile: config_server/Dockerfile
    container_name: config-server
    networks:
      - my-network
    ports:
      - "8070:8070"
    environment:
      - SPRING_APPLICATION_NAME=config-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - EUREKA_INSTANSE_PREFERIPADDRESS=true
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINTS_HEALTH_SHOW_DETAILS=always

  gateway:
    build:
      context: gateway
      dockerfile: gateway/Dockerfile
    depends_on:
      - config-server
    networks:
      - my-network
    ports:
      - "80:80"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8070
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - EUREKA_INSTANSE_PREFERIPADDRESS=true
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINTS_HEALTH_SHOW_DETAILS=always

  store-authorization:
    build:
      context: store_authorization
      dockerfile: store_authorization/Dockerfile
    networks:
      - my-network
    ports:
      - "8080:8080"
    depends_on:
      - authorization-db
      - token-storage
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8070
      - SPRING_DATASOURCE_URL=jdbc:postgresql://authorization-db:5432/store_authorization
      - SPRING_DATA_REDIS_HOST=token-storage
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - EUREKA_INSTANSE_PREFERIPADDRESS=true
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINTS_HEALTH_SHOW_DETAILS=always

  optical-shop:
    build:
      context: optical_shop
    networks:
      - my-network
    ports:
      - "8888:8888"
    depends_on:
      - optical-db
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8070
      - SPRING_DATASOURCE_URL=jdbc:postgresql://optical-db:5432/OpticalShop
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - EUREKA_INSTANSE_PREFERIPADDRESS=true
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINTS_HEALTH_SHOW_DETAILS=always

  authorization-db:
    image: postgres
    restart: always
    volumes:
      - authorization-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wtf123
      - POSTGRES_DB=store_authorization
    networks:
      - my-network
    ports:
      - "5434:5432"

  optical-db:
    image: postgres
    restart: always
    volumes:
      - optical-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wtf123
      - POSTGRES_DB=OpticalShop
    networks:
      - my-network
    ports:
      - "5433:5432"

  token-storage:
    image: redis
    restart: always
    networks:
      - my-network
    ports:
      - "6379:6379"

volumes:
  authorization-db-data:
  optical-db-data:
networks:
  my-network:
    driver: bridge