apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: store-authorization
  name: store-authorization
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: store-authorization
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: store-authorization
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: EUREKA_INSTANSE_PREFERIPADDRESS
              value: "true"
            - name: MANAGEMENT_ENDPOINTS_HEALTH_SHOW_DETAILS
              value: always
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: '*'
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-server:8070
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://authorization-db:5432/store-authorization
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: wtf123
            - name: SPRING_DATA_REDIS_HOST
              value: token-storage
          image: localhost:5000/store-authorization:minikube
          name: store-authorization
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
