server:
  port: 80

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: DEBUG

spring:
  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
        ssl:
          useInsecureTrustManager: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: login
          uri: lb://STORE-AUTHORIZATION
          predicates:
            - Path=/auth/login
          filters:
            - RewritePath=/auth/login, /auth/token

        - id: refresh
          uri: lb://STORE-AUTHORIZATION
          predicates:
            - Path=/auth/refresh

        - id: comment_endpoints
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/product/comment/{*product_id}

        - id: upload_image_endpoint
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/admin/product/image/upload/{*product_id}
          filters:
            - TokenValidationFilter
            - AdminFilter

        - id: delete_image_endpoint
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/admin/product/image/delete/{*product_id}
          filters:
            - TokenValidationFilter
            - AdminFilter

        - id: download_image_endpoint
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/product/image/download/{*product_id}

        - id: product_endpoints
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/admin/product/{*id}
          filters:
            - TokenValidationFilter
            - AdminFilter

        - id: add_product
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/product/add/{*product_id}
          filters:
            - TokenValidationFilter

        - id: get_product
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/product/{*id}

        - id: get_products
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/product

        - id: delete_comment_endpoint
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/admin/comment/{*comment_id}
          filters:
            - TokenValidationFilter
            - AdminFilter

        - id: create_product
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/admin/product
          filters:
            - TokenValidationFilter
            - AdminFilter

        - id: update_product
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/admin/product
          filters:
            - TokenValidationFilter
            - AdminFilter

        - id: create_order
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/order/create
          filters:
           - TokenValidationFilter

        - id: get_orders
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/order
          filters:
           - TokenValidationFilter

        - id: get_orders_by_login
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/order/{*login}
          filters:
           - TokenValidationFilter

        - id: update_order_state
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/admin/order
          filters:
            - TokenValidationFilter
            - AdminFilter