server:
  port: 80

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: DEBUG

spring:
  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: login
          uri: lb://STORE-AUTHORIZATION
          predicates:
            - Path=/auth/login
          filters:
            - RewritePath=/auth/login, /auth/token

        - id: refresh
          uri: lb://STORE-AUTHORIZATION
          predicates:
            - Path=/auth/refresh

        - id: product_endpoints
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/admin/product/{*id}
          filters:
            - TokenValidationFilter
            - AdminFilter

        - id: get_product
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/product/{*id}

        - id: get_products
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/product

        - id: comment_endpoints
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/product/comment/{*product_id}
          filters:
            - TokenValidationFilter

        - id: delete_comment_endpoint
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/admin/comment/{*comment_id}
          filters:
            - TokenValidationFilter
            - AdminFilter

        - id: create_product
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/admin/product
          filters:
            - TokenValidationFilter
            - AdminFilter

        - id: update_product
          uri: lb://OPTICAL-SHOP
          predicates:
            - Path=/admin/product
          filters:
            - TokenValidationFilter
            - AdminFilter