global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:80']
  - job_name: 'store-authorization'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['store-authorization:8080']
  - job_name: 'optical-shop'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['optical-shop:8888']